[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "accessiplot"
authors = [{name = "Charles Drotar", email = "drotarcharles@gmail.com"}]
dynamic = ["version", "description"]